# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Hello
on: [push]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: say hello
        run: echo 'hello world'
      - name: Create status
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "state": "success",
            "context": "dummy test",
            "target_url": "${{ github.event.workflow_run.html_url }}"
            }' \
          --fail
